/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package tjmike.datastax.datadecoder;

import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


@SpringBootApplication
@EnableAsync
public class DataDecoder { // implements CommandLineRunner {
	private static Logger s_log = LoggerFactory.getLogger(DataDecoder.class);



    public static void main(String[] args) {

        SpringApplication app = new SpringApplication(DataDecoder.class);
	// Turn Spring banner off
        app.setBannerMode(Banner.Mode.OFF);
        app.run(args);

    }
}
