/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package tjmike.datastax.datapump;

import java.time.Instant;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.Banner;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


@SpringBootApplication
@EnableAsync
@EnableScheduling
public class DataPump { // implements CommandLineRunner {
	private static Logger s_log = LoggerFactory.getLogger(DataPump.class);
	private static final long s_SessionID = Instant.now().getEpochSecond();


//    private  DataPumper d_dataPumper;
    private DataPumpPusher d_dataPumpPusher;


    @Autowired
    public DataPump(DataPumpPusher dataPumpPusher) {
        this.d_dataPumpPusher = dataPumpPusher;
    }

    public static void main(String[] args) throws Exception {
        SpringApplication app = new SpringApplication(DataPump.class);
	// Turn Spring banner off
        app.setBannerMode(Banner.Mode.OFF);
        app.run(args);

    }



}
